DROP TABLE IF EXISTS STUDENTS;
CREATE TABLE STUDENTS(ID BIGINT PRIMARY KEY auto_increment, NAME VARCHAR(255));

DROP TABLE IF EXISTS LIBRARY;
CREATE TABLE LIBRARY(ID BIGINT PRIMARY KEY auto_increment, BOOKID BIGINT, STUDENTID BIGINT);