DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY auto_increment, NAME VARCHAR(255), GENRE BIGINT, AUTHOR BIGINT);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY auto_increment, NAME VARCHAR(255));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY auto_increment, NAME VARCHAR(255));

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS(ID BIGINT PRIMARY KEY auto_increment, TEXT MEDIUMTEXT, BOOK BIGINT, AUTHOR VARCHAR(255) );

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(ID BIGINT PRIMARY KEY auto_increment, USERNAME VARCHAR(255), PASSWORD VARCHAR(255),
                    ENABLED INTEGER);

DROP TABLE IF EXISTS AUTHORITIES;
CREATE TABLE AUTHORITIES(ID BIGINT PRIMARY KEY auto_increment, USERNAME VARCHAR(255), AUTHORITY VARCHAR(255));